title: Taraxa Validator Documentation
email: contact@cryptobauer.com
description: >-
  Documentation for validator node operators for the Taraxa blockDAG network.
baseurl: ""
url: "https://docs.cryptobauer.com"

permalink: pretty # generate pretty permalinks

defaults:
  - scope:
      path: "docs/rpc"
      type: "pages"
    values:
      layout: "default"
      permalink: /rpc/:basename/

theme: just-the-docs
color_scheme: taraxa
search_enabled: false

nav_open: true

mermaid:
  version: 11.6.0

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/cryptobauer/docs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
